"""Public configuration, credentials, Profile, readiness, and probe surface.

The package is split internally by change reason: ordinary TOML documents,
owner-only credentials, persistent Browser profiles, Browser policy/status,
and explicit probes.  Callers continue to import :mod:`sciretriever.configuration`;
the package layout is a code-governance detail, not a separate product module.
"""

from sciretriever.configuration.browser_access import (
    browser_access_status,
    configured_browser_group_policies,
    eligible_production_browser_access_keys,
    tightened_browser_group_policies,
)
from sciretriever.configuration.browser_profiles import (
    BrowserProfileCancellation,
    BrowserProfileHandle,
    BrowserProfileRuntimeLease,
    browser_profile_path,
    browser_profile_status,
    initialize_browser_profile,
    remove_browser_profile,
    resolve_browser_profile,
)
from sciretriever.configuration.credential_edits import (
    remove_core_credentials,
    remove_credentials,
    set_core_credentials,
    set_credentials,
    update_core_service_configuration,
)
from sciretriever.configuration.credentials import (
    CredentialLookup,
    RuntimeSecretLookup,
    configurable_credential_providers,
    configuration_service_origin,
    core_credential_section_exists,
    credential_diagnostic,
    credential_field_specs,
    credential_path,
    credential_section_exists,
    credential_status_for,
    load_credentials,
    load_runtime_secrets,
)
from sciretriever.configuration.documents import (
    configuration_diff,
    configure_browser_access_profile,
    load_configuration,
    load_editable_configuration,
    load_selected_configuration,
    parse_configuration,
    select_configuration_edit_path,
    select_configuration_path,
    update_configuration_sections,
)
from sciretriever.configuration.errors import ConfigurationError
from sciretriever.configuration.status import (
    BrowserConfigurationProbePort,
    ConfigurationProbePort,
    configuration_runtime_status,
    configuration_status,
    run_browser_configuration_probe,
    run_configuration_probes,
)
from sciretriever.model.configuration import (
    AcquisitionSourcesConfig,
    BrowserAccessStatus,
    BrowserConfigurationProbeResult,
    BrowserProfilePresence,
    BrowserProfileStatus,
    Configuration,
    ConfigurationDiagnostic,
    ConfigurationProbeResult,
    ConfigurationProbeSummary,
    ConfigurationStatus,
    CredentialStatus,
    ProviderCapability,
    ProviderCredentialStatus,
    ProviderName,
    UnpaywallAcquisitionConfig,
)

__all__ = (
    "AcquisitionSourcesConfig",
    "BrowserAccessStatus",
    "BrowserConfigurationProbePort",
    "BrowserConfigurationProbeResult",
    "BrowserProfileCancellation",
    "BrowserProfileHandle",
    "BrowserProfilePresence",
    "BrowserProfileRuntimeLease",
    "BrowserProfileStatus",
    "Configuration",
    "ConfigurationDiagnostic",
    "ConfigurationError",
    "ConfigurationProbePort",
    "ConfigurationProbeResult",
    "ConfigurationProbeSummary",
    "ConfigurationStatus",
    "CredentialLookup",
    "CredentialStatus",
    "ProviderCapability",
    "ProviderCredentialStatus",
    "ProviderName",
    "RuntimeSecretLookup",
    "UnpaywallAcquisitionConfig",
    "browser_access_status",
    "browser_profile_path",
    "browser_profile_status",
    "configurable_credential_providers",
    "configure_browser_access_profile",
    "configured_browser_group_policies",
    "configuration_diff",
    "configuration_runtime_status",
    "configuration_service_origin",
    "configuration_status",
    "core_credential_section_exists",
    "credential_diagnostic",
    "credential_field_specs",
    "credential_path",
    "credential_section_exists",
    "credential_status_for",
    "eligible_production_browser_access_keys",
    "initialize_browser_profile",
    "load_configuration",
    "load_credentials",
    "load_editable_configuration",
    "load_runtime_secrets",
    "load_selected_configuration",
    "parse_configuration",
    "remove_browser_profile",
    "remove_core_credentials",
    "remove_credentials",
    "resolve_browser_profile",
    "run_browser_configuration_probe",
    "run_configuration_probes",
    "select_configuration_edit_path",
    "select_configuration_path",
    "set_core_credentials",
    "set_credentials",
    "tightened_browser_group_policies",
    "update_configuration_sections",
    "update_core_service_configuration",
)
