from typing import Final

COLLECTION_DDL: Final = (
    "CREATE TABLE collections(id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE,description TEXT,topic_conditions_json TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,CHECK(topic_conditions_json IS NULL OR json_valid(topic_conditions_json))) STRICT",
    "CREATE TABLE collection_runs(id TEXT PRIMARY KEY,collection_id TEXT NOT NULL REFERENCES collections(id) ON DELETE CASCADE,mode TEXT NOT NULL CHECK(mode IN ('topic','citation')),topic_conditions_json TEXT,citation_input_json TEXT,requested_advance_to TEXT NOT NULL CHECK(requested_advance_to IN ('unreviewed','asset-ready','light-text-ready','completed')),status TEXT NOT NULL CHECK(status IN ('created','running','no-target','completed','partial','failed','interrupted')),stop_reason TEXT,advancement_batch_id TEXT UNIQUE,discovered_count INTEGER,accepted_count INTEGER,new_member_count INTEGER,existing_member_count INTEGER,missing_count INTEGER,source_failure_count INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,CHECK((mode='topic' AND topic_conditions_json IS NOT NULL AND citation_input_json IS NULL) OR (mode='citation' AND topic_conditions_json IS NULL AND citation_input_json IS NOT NULL)),CHECK(topic_conditions_json IS NULL OR json_valid(topic_conditions_json)),CHECK(citation_input_json IS NULL OR json_valid(citation_input_json)),CHECK((status IN ('created','running') AND discovered_count IS NULL AND accepted_count IS NULL AND new_member_count IS NULL AND existing_member_count IS NULL AND missing_count IS NULL AND source_failure_count IS NULL) OR (status IN ('no-target','completed','partial','failed','interrupted') AND discovered_count>=0 AND accepted_count>=0 AND new_member_count>=0 AND existing_member_count>=0 AND missing_count>=0 AND source_failure_count>=0 AND accepted_count=new_member_count+existing_member_count AND discovered_count>=accepted_count+missing_count))) STRICT",
    "CREATE TABLE collection_source_results(collection_run_id TEXT NOT NULL REFERENCES collection_runs(id) ON DELETE CASCADE,source_ordinal INTEGER NOT NULL CHECK(source_ordinal>=0),source_name TEXT NOT NULL CHECK(length(trim(source_name))>0),discovered_count INTEGER NOT NULL CHECK(discovered_count>=0),accepted_count INTEGER NOT NULL CHECK(accepted_count>=0),missing_count INTEGER NOT NULL CHECK(missing_count>=0),failure_code TEXT,failure_reason TEXT,failure_action TEXT,retryable INTEGER CHECK(retryable IN (0,1)),PRIMARY KEY(collection_run_id,source_ordinal),UNIQUE(collection_run_id,source_name),CHECK(discovered_count=accepted_count+missing_count),CHECK((failure_code IS NULL AND failure_reason IS NULL AND failure_action IS NULL AND retryable IS NULL) OR (length(trim(failure_code))>0 AND length(trim(failure_reason))>0 AND length(trim(failure_action))>0 AND retryable IS NOT NULL))) STRICT",
    "CREATE TABLE collection_memberships(id TEXT PRIMARY KEY,collection_id TEXT NOT NULL REFERENCES collections(id) ON DELETE CASCADE,work_id TEXT NOT NULL REFERENCES works(id) ON DELETE CASCADE,first_collection_run_id TEXT NOT NULL REFERENCES collection_runs(id),UNIQUE(collection_id,work_id)) STRICT",
    "CREATE TABLE collection_causes(id TEXT PRIMARY KEY,membership_id TEXT NOT NULL REFERENCES collection_memberships(id) ON DELETE CASCADE,collection_run_id TEXT NOT NULL REFERENCES collection_runs(id),kind TEXT NOT NULL CHECK(kind IN ('topic-match','seed','reference','cited-by')),source TEXT,condition TEXT,seed_work_id TEXT) STRICT",
    "CREATE TABLE collection_paths(id TEXT PRIMARY KEY,membership_id TEXT NOT NULL REFERENCES collection_memberships(id) ON DELETE CASCADE,collection_run_id TEXT NOT NULL REFERENCES collection_runs(id),direction TEXT CHECK(direction IN ('references','cited-by')),depth INTEGER NOT NULL CHECK(depth>=0),work_ids_json TEXT NOT NULL CHECK(json_valid(work_ids_json))) STRICT",
)
