"""Production publisher/access profile catalog.

Only capabilities with current repository evidence are declared here.  A
profile can be useful for public/API planning without implying that a Browser
route is production-ready.
"""

from __future__ import annotations

from datetime import date
from typing import Final

from sciretriever.acquisition.access_profiles import (
    PolicyEvidence,
    ProfileProductionStatus,
    PublisherAccessEvidence,
    PublisherAccessProfile,
    PublisherAccessProfileCatalog,
)
from sciretriever.acquisition.profile_verification import PublisherAccessVerificationMatrix
from sciretriever.acquisition.sources.browser_rules import PRODUCTION_BROWSER_RULE_CATALOG
from sciretriever.network.browser_scheduler import BrowserGroupPolicy

ACS_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="acs-publications",
    platform_key="acs-publications",
    landing_origins=("https://pubs.acs.org",),
    asset_origins=("https://pubs.acs.org",),
    stable_locator_namespaces=(),
    provider_record_names=(),
    weak_doi_prefixes=("10.1021",),
    weak_publisher_names=("acs publications", "american chemical society"),
    public_route_keys=(),
    api_route_keys=(),
    browser_route_key=None,
    browser_allowed_origins=(),
    browser_rate_limit_group=None,
    browser_session_key=None,
    browser_rule_id=None,
    browser_rule_revision=None,
    policy_evidence=PolicyEvidence.OFFICIAL,
    policy_revision="acs-publications-terms-2021-05",
    production_status=ProfileProductionStatus.UNSUPPORTED,
    evidence=PublisherAccessEvidence(
        display_name="ACS Publications",
        product_name="ACS Publications article platform",
        official_references=(
            "https://pubs.acs.org/",
            "https://solutions.acs.org/solutions/text-and-data-mining/",
            (
                "https://solutions.acs.org/wp-content/uploads/2025/04/"
                "ACS-Publications-Terms-and-Conditions-of-Use.pdf"
            ),
        ),
        access_terms_references=(
            (
                "https://solutions.acs.org/wp-content/uploads/2025/04/"
                "ACS-Publications-Terms-and-Conditions-of-Use.pdf"
            ),
        ),
        rate_limit_references=(
            (
                "https://solutions.acs.org/wp-content/uploads/2025/04/"
                "ACS-Publications-Terms-and-Conditions-of-Use.pdf"
            ),
        ),
        verification_date=date(2026, 8, 15),
        evidence_revision="acs-browser-unsupported-2026-08-15",
        notes_reference="docs/notes/providers/acs.md",
        fixture_reference="tests/fixtures/acquisition/profiles/acs-publications.json",
    ),
)

ACM_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="acm-digital-library",
    platform_key="acm-digital-library",
    landing_origins=("https://dl.acm.org",),
    asset_origins=("https://dl.acm.org",),
    stable_locator_namespaces=(),
    provider_record_names=(),
    weak_doi_prefixes=("10.1145",),
    weak_publisher_names=("acm", "association for computing machinery"),
    public_route_keys=(),
    api_route_keys=(),
    browser_route_key=None,
    browser_allowed_origins=(),
    browser_rate_limit_group=None,
    browser_session_key=None,
    browser_rule_id=None,
    browser_rule_revision=None,
    policy_evidence=PolicyEvidence.OFFICIAL,
    policy_revision="acm-dl-open-access-and-usage-2026-08-15",
    production_status=ProfileProductionStatus.UNSUPPORTED,
    evidence=PublisherAccessEvidence(
        display_name="ACM Digital Library",
        product_name="ACM Digital Library Basic and Premium",
        official_references=(
            "https://www.acm.org/publications/openaccess",
            "https://libraries.acm.org/digital-library/platform-and-features",
            "https://libraries.acm.org/digital-library/policies",
            "https://libraries.acm.org/subscriptions-access/authentication",
            "https://dl.acm.org/robots.txt",
        ),
        access_terms_references=("https://libraries.acm.org/digital-library/policies",),
        rate_limit_references=(
            "https://libraries.acm.org/digital-library/policies",
            "https://dl.acm.org/robots.txt",
        ),
        verification_date=date(2026, 8, 15),
        evidence_revision="acm-dl-automated-access-unsupported-2026-08-15",
        notes_reference="docs/notes/providers/acm.md",
        fixture_reference="tests/fixtures/acquisition/profiles/acm-digital-library.json",
    ),
)

AIP_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="aip-publishing",
    platform_key="aip-publishing",
    landing_origins=("https://pubs.aip.org",),
    asset_origins=("https://pubs.aip.org",),
    stable_locator_namespaces=(),
    provider_record_names=(),
    weak_doi_prefixes=("10.1063",),
    weak_publisher_names=(
        "aip publishing",
        "american institute of physics",
    ),
    public_route_keys=(),
    api_route_keys=(),
    browser_route_key=None,
    browser_allowed_origins=(),
    browser_rate_limit_group=None,
    browser_session_key=None,
    browser_rule_id=None,
    browser_rule_revision=None,
    policy_evidence=PolicyEvidence.OFFICIAL,
    policy_revision="aip-terms-of-use-2023-04-20",
    production_status=ProfileProductionStatus.UNSUPPORTED,
    evidence=PublisherAccessEvidence(
        display_name="AIP Publishing",
        product_name="AIP Publishing journals platform",
        official_references=(
            "https://pubs.aip.org/",
            "https://publishing.aip.org/terms-of-use/",
            "https://publishing.aip.org/resources/librarians/licensing/access/",
            "https://publishing.aip.org/resources/librarians/licensing/licenses/",
            (
                "https://publishing.aip.org/resources/researchers/"
                "rights-and-permissions/permissions/"
            ),
            ("https://publishing.aip.org/resources/researchers/open-science/public-access/"),
            "https://pubs.aip.org/robots.txt",
        ),
        access_terms_references=(
            "https://publishing.aip.org/terms-of-use/",
            "https://publishing.aip.org/resources/librarians/licensing/access/",
        ),
        rate_limit_references=(
            "https://publishing.aip.org/terms-of-use/",
            "https://pubs.aip.org/robots.txt",
        ),
        verification_date=date(2026, 8, 15),
        evidence_revision="aip-automated-access-unsupported-2026-08-15",
        notes_reference="docs/notes/providers/aip.md",
        fixture_reference="tests/fixtures/acquisition/profiles/aip-publishing.json",
    ),
)

AMERICAN_MATHEMATICAL_SOCIETY_ACCESS_PROFILE: Final[PublisherAccessProfile] = (
    PublisherAccessProfile(
        access_key="american-mathematical-society",
        platform_key="american-mathematical-society",
        landing_origins=("https://www.ams.org",),
        asset_origins=("https://www.ams.org",),
        stable_locator_namespaces=(),
        provider_record_names=(),
        weak_doi_prefixes=("10.1090",),
        weak_publisher_names=(
            "american mathematical society",
            "ams mathematics",
        ),
        public_route_keys=(),
        api_route_keys=(),
        browser_route_key=None,
        browser_allowed_origins=(),
        browser_rate_limit_group=None,
        browser_session_key=None,
        browser_rule_id=None,
        browser_rule_revision=None,
        policy_evidence=PolicyEvidence.OFFICIAL,
        policy_revision="ams-managed-robots-2026-08-15",
        production_status=ProfileProductionStatus.UNSUPPORTED,
        evidence=PublisherAccessEvidence(
            display_name="American Mathematical Society",
            product_name="AMS journals platform",
            official_references=(
                "https://www.ams.org/journals",
                "https://www.ams.org/publications/journals/open-access",
                "https://www.ams.org/publications/journals/subscriber-information",
                "https://www.ams.org/about-us/governance/terms-of-use",
                "https://www.ams.org/robots.txt",
            ),
            access_terms_references=(
                "https://www.ams.org/about-us/governance/terms-of-use",
                "https://www.ams.org/publications/journals/subscriber-information",
            ),
            rate_limit_references=("https://www.ams.org/robots.txt",),
            verification_date=date(2026, 8, 15),
            evidence_revision="ams-automated-access-unsupported-2026-08-15",
            notes_reference="docs/notes/providers/american-mathematical-society.md",
            fixture_reference=(
                "tests/fixtures/acquisition/profiles/american-mathematical-society.json"
            ),
        ),
    )
)

ANNUAL_REVIEWS_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="annual-reviews",
    platform_key="annual-reviews",
    landing_origins=("https://www.annualreviews.org",),
    asset_origins=("https://www.annualreviews.org",),
    stable_locator_namespaces=(),
    provider_record_names=(),
    weak_doi_prefixes=("10.1146",),
    weak_publisher_names=("annual reviews",),
    public_route_keys=(),
    api_route_keys=(),
    browser_route_key=None,
    browser_allowed_origins=(),
    browser_rate_limit_group=None,
    browser_session_key=None,
    browser_rule_id=None,
    browser_rule_revision=None,
    policy_evidence=PolicyEvidence.OFFICIAL,
    policy_revision="annual-reviews-robots-2026-08-15",
    production_status=ProfileProductionStatus.UNSUPPORTED,
    evidence=PublisherAccessEvidence(
        display_name="Annual Reviews",
        product_name="Annual Reviews journals platform",
        official_references=(
            "https://www.annualreviews.org/",
            "https://www.annualreviews.org/page/about/terms",
            "https://www.annualreviews.org/page/librarians/subscribe-to-open",
            "https://www.annualreviews.org/robots.txt",
        ),
        access_terms_references=("https://www.annualreviews.org/page/about/terms",),
        rate_limit_references=("https://www.annualreviews.org/robots.txt",),
        verification_date=date(2026, 8, 15),
        evidence_revision="annual-reviews-automated-access-unsupported-2026-08-15",
        notes_reference="docs/notes/providers/annual-reviews.md",
        fixture_reference="tests/fixtures/acquisition/profiles/annual-reviews.json",
    ),
)

APS_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="aps-journals",
    platform_key="aps-journals",
    landing_origins=(
        "https://journals.aps.org",
        "https://link.aps.org",
    ),
    asset_origins=("https://journals.aps.org",),
    stable_locator_namespaces=(),
    provider_record_names=(),
    weak_doi_prefixes=("10.1103",),
    weak_publisher_names=(
        "american physical society",
        "physical review",
    ),
    public_route_keys=(),
    api_route_keys=(),
    browser_route_key=None,
    browser_allowed_origins=(),
    browser_rate_limit_group=None,
    browser_session_key=None,
    browser_rule_id=None,
    browser_rule_revision=None,
    policy_evidence=PolicyEvidence.OFFICIAL,
    policy_revision="aps-managed-robots-2026-08-15",
    production_status=ProfileProductionStatus.UNSUPPORTED,
    evidence=PublisherAccessEvidence(
        display_name="American Physical Society",
        product_name="Physical Review journals platform",
        official_references=(
            "https://journals.aps.org/",
            "https://journals.aps.org/info/terms",
            "https://journals.aps.org/robots.txt",
            "https://link.aps.org/robots.txt",
        ),
        access_terms_references=("https://journals.aps.org/info/terms",),
        rate_limit_references=(
            "https://journals.aps.org/robots.txt",
            "https://link.aps.org/robots.txt",
        ),
        verification_date=date(2026, 8, 15),
        evidence_revision="aps-automated-access-unsupported-2026-08-15",
        notes_reference="docs/notes/providers/aps.md",
        fixture_reference="tests/fixtures/acquisition/profiles/aps-journals.json",
    ),
)

COPERNICUS_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="copernicus-publications",
    platform_key="copernicus-publications",
    landing_origins=(
        "https://publications.copernicus.org",
        "https://www.copernicus.org",
    ),
    asset_origins=(
        "https://publications.copernicus.org",
        "https://www.copernicus.org",
    ),
    stable_locator_namespaces=(),
    provider_record_names=(),
    weak_doi_prefixes=("10.5194",),
    weak_publisher_names=(
        "copernicus publications",
        "copernicus gmbh",
    ),
    public_route_keys=(),
    api_route_keys=(),
    browser_route_key=None,
    browser_allowed_origins=(),
    browser_rate_limit_group=None,
    browser_session_key=None,
    browser_rule_id=None,
    browser_rule_revision=None,
    policy_evidence=PolicyEvidence.OFFICIAL,
    policy_revision="copernicus-public-robots-2026-08-15",
    production_status=ProfileProductionStatus.UNSUPPORTED,
    evidence=PublisherAccessEvidence(
        display_name="Copernicus Publications",
        product_name="Copernicus Publications open-access journals",
        official_references=(
            "https://publications.copernicus.org/",
            "https://publications.copernicus.org/services/open-access_publishing.html",
            "https://publications.copernicus.org/for_authors/licence_and_copyright.html",
            "https://publications.copernicus.org/services/xml_harvesting_and_oai-pmh.html",
            "https://publications.copernicus.org/robots.txt",
        ),
        access_terms_references=(
            "https://publications.copernicus.org/for_authors/licence_and_copyright.html",
            "https://publications.copernicus.org/for_authors/general_terms.html",
        ),
        rate_limit_references=("https://publications.copernicus.org/robots.txt",),
        verification_date=date(2026, 8, 15),
        evidence_revision="copernicus-public-route-unregistered-2026-08-15",
        notes_reference="docs/notes/providers/copernicus.md",
        fixture_reference=("tests/fixtures/acquisition/profiles/copernicus-publications.json"),
    ),
)

CORE_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="core-open-access",
    platform_key="core-api",
    landing_origins=("https://core.ac.uk",),
    asset_origins=("https://api.core.ac.uk", "https://core.ac.uk"),
    stable_locator_namespaces=(),
    provider_record_names=("core",),
    weak_doi_prefixes=(),
    weak_publisher_names=(),
    public_route_keys=(),
    api_route_keys=("api:core",),
    browser_route_key=None,
    browser_allowed_origins=(),
    browser_rate_limit_group=None,
    browser_session_key=None,
    browser_rule_id=None,
    browser_rule_revision=None,
    policy_evidence=PolicyEvidence.OFFICIAL,
    policy_revision="core-v3-2026-08-13",
    production_status=ProfileProductionStatus.PRODUCTION_READY,
    evidence=PublisherAccessEvidence(
        display_name="CORE",
        product_name="CORE API v3",
        official_references=(
            "https://api.core.ac.uk/docs/v3",
            "https://api.core.ac.uk/swagger/v3.json",
            "https://core.ac.uk/services/api",
        ),
        access_terms_references=("https://core.ac.uk/terms",),
        rate_limit_references=("https://api.core.ac.uk/docs/v3",),
        verification_date=date(2026, 8, 15),
        evidence_revision="core-v3-2026-08-15",
        notes_reference="docs/notes/providers/core.md",
        fixture_reference="tests/fixtures/acquisition/profiles/core-open-access.json",
    ),
)

ELSEVIER_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="elsevier-sciencedirect",
    platform_key="sciencedirect",
    landing_origins=(
        "https://www.sciencedirect.com",
        "https://linkinghub.elsevier.com",
    ),
    asset_origins=(
        "https://api.elsevier.com",
        "https://www.sciencedirect.com",
        "https://linkinghub.elsevier.com",
        "https://pdf.sciencedirectassets.com",
    ),
    stable_locator_namespaces=("pii", "elsevier-article-eid"),
    provider_record_names=(),
    weak_doi_prefixes=("10.1016",),
    weak_publisher_names=("elsevier", "science direct", "sciencedirect"),
    public_route_keys=(),
    api_route_keys=("api:elsevier-article-object",),
    browser_route_key=None,
    browser_allowed_origins=(),
    browser_rate_limit_group=None,
    browser_session_key=None,
    browser_rule_id=None,
    browser_rule_revision=None,
    policy_evidence=PolicyEvidence.OFFICIAL,
    policy_revision="elsevier-article-direct-object-2026-08-18",
    production_status=ProfileProductionStatus.PRODUCTION_READY,
    evidence=PublisherAccessEvidence(
        display_name="Elsevier / ScienceDirect",
        product_name="Article Retrieval direct PDF and Object Retrieval APIs",
        official_references=(
            "https://dev.elsevier.com/documentation/ArticleRetrievalAPI.wadl",
            "https://dev.elsevier.com/documentation/ObjectRetrievalAPI.wadl",
            "https://dev.elsevier.com/api_docs.html",
        ),
        access_terms_references=("https://dev.elsevier.com/policy.html",),
        rate_limit_references=("https://dev.elsevier.com/api_key_settings.html",),
        verification_date=date(2026, 8, 18),
        evidence_revision="elsevier-article-direct-object-2026-08-18",
        notes_reference="docs/notes/providers/elsevier.md",
        fixture_reference=("tests/fixtures/acquisition/profiles/elsevier-sciencedirect.json"),
    ),
)

FRONTIERS_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="frontiers",
    platform_key="frontiers",
    landing_origins=("https://www.frontiersin.org",),
    asset_origins=("https://www.frontiersin.org",),
    stable_locator_namespaces=(),
    provider_record_names=(),
    weak_doi_prefixes=("10.3389",),
    weak_publisher_names=(
        "frontiers",
        "frontiers media",
    ),
    public_route_keys=(),
    api_route_keys=(),
    browser_route_key=None,
    browser_allowed_origins=(),
    browser_rate_limit_group=None,
    browser_session_key=None,
    browser_rule_id=None,
    browser_rule_revision=None,
    policy_evidence=PolicyEvidence.OFFICIAL,
    policy_revision="frontiers-public-robots-2026-08-15",
    production_status=ProfileProductionStatus.UNSUPPORTED,
    evidence=PublisherAccessEvidence(
        display_name="Frontiers",
        product_name="Frontiers journals platform",
        official_references=(
            "https://www.frontiersin.org/",
            "https://www.frontiersin.org/about/open-access",
            "https://www.frontiersin.org/legal/terms-and-conditions",
            "https://www.frontiersin.org/robots.txt",
        ),
        access_terms_references=("https://www.frontiersin.org/legal/terms-and-conditions",),
        rate_limit_references=("https://www.frontiersin.org/robots.txt",),
        verification_date=date(2026, 8, 15),
        evidence_revision="frontiers-public-route-unregistered-2026-08-15",
        notes_reference="docs/notes/providers/frontiers.md",
        fixture_reference="tests/fixtures/acquisition/profiles/frontiers.json",
    ),
)

IEEE_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="ieee-xplore",
    platform_key="ieee-xplore",
    landing_origins=("https://ieeexplore.ieee.org",),
    asset_origins=("https://ieeexplore.ieee.org",),
    stable_locator_namespaces=("ieee-arnumber",),
    provider_record_names=(),
    weak_doi_prefixes=("10.1109",),
    weak_publisher_names=("ieee", "institute of electrical and electronics engineers"),
    public_route_keys=(),
    api_route_keys=(),
    browser_route_key=None,
    browser_allowed_origins=(),
    browser_rate_limit_group=None,
    browser_session_key=None,
    browser_rule_id=None,
    browser_rule_revision=None,
    policy_evidence=PolicyEvidence.OFFICIAL,
    policy_revision="ieee-xplore-api-terms-2026-08-15",
    production_status=ProfileProductionStatus.UNSUPPORTED,
    evidence=PublisherAccessEvidence(
        display_name="IEEE Xplore",
        product_name="IEEE Xplore article and Full-Text Access platform",
        official_references=(
            "https://ieeexplore.ieee.org/",
            "https://developer.ieee.org/docs",
            "https://developer.ieee.org/Chargeable_Full_Text_Requests",
        ),
        access_terms_references=("https://developer.ieee.org/API_Terms_of_Use2",),
        rate_limit_references=("https://developer.ieee.org/API_Terms_of_Use2",),
        verification_date=date(2026, 8, 15),
        evidence_revision="ieee-access-unsupported-2026-08-15",
        notes_reference="docs/notes/providers/ieee.md",
        fixture_reference="tests/fixtures/acquisition/profiles/ieee-xplore.json",
    ),
)

IOP_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="iopscience",
    platform_key="iopscience",
    landing_origins=("https://iopscience.iop.org",),
    asset_origins=("https://iopscience.iop.org",),
    stable_locator_namespaces=(),
    provider_record_names=(),
    weak_doi_prefixes=("10.1088",),
    weak_publisher_names=(
        "iop publishing",
        "institute of physics publishing",
        "iopscience",
    ),
    public_route_keys=(),
    api_route_keys=(),
    browser_route_key=None,
    browser_allowed_origins=(),
    browser_rate_limit_group=None,
    browser_session_key=None,
    browser_rule_id=None,
    browser_rule_revision=None,
    policy_evidence=PolicyEvidence.OFFICIAL,
    policy_revision="iop-tdm-policy-2026-07",
    production_status=ProfileProductionStatus.UNSUPPORTED,
    evidence=PublisherAccessEvidence(
        display_name="IOPscience",
        product_name="IOPscience journals platform",
        official_references=(
            "https://ioppublishing.org/legal/textanddataminingpolicy/",
            "https://ioppublishing.org/terms-conditions/",
            "https://ioppublishing.org/librarians/licencing/",
            (
                "https://ioppublishing.org/news/"
                "iop-publishing-collaborates-with-openathens-and-seamlessaccess-"
                "to-improve-user-experience/"
            ),
            "https://iopscience.iop.org/robots.txt",
        ),
        access_terms_references=(
            "https://ioppublishing.org/legal/textanddataminingpolicy/",
            "https://ioppublishing.org/terms-conditions/",
        ),
        rate_limit_references=(
            "https://ioppublishing.org/legal/textanddataminingpolicy/",
            "https://iopscience.iop.org/robots.txt",
        ),
        verification_date=date(2026, 8, 15),
        evidence_revision="iopscience-automated-access-unsupported-2026-08-15",
        notes_reference="docs/notes/providers/iop.md",
        fixture_reference="tests/fixtures/acquisition/profiles/iopscience.json",
    ),
)

MDPI_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="mdpi",
    platform_key="mdpi",
    landing_origins=(
        "https://www.mdpi.com",
        "https://mdpi.com",
    ),
    asset_origins=(
        "https://www.mdpi.com",
        "https://mdpi.com",
    ),
    stable_locator_namespaces=(),
    provider_record_names=(),
    weak_doi_prefixes=("10.3390",),
    weak_publisher_names=(
        "mdpi",
        "multidisciplinary digital publishing institute",
    ),
    public_route_keys=(),
    api_route_keys=(),
    browser_route_key=None,
    browser_allowed_origins=(),
    browser_rate_limit_group=None,
    browser_session_key=None,
    browser_rule_id=None,
    browser_rule_revision=None,
    policy_evidence=PolicyEvidence.UNVERIFIED,
    policy_revision="mdpi-public-policy-unreviewed-2026-08-15",
    production_status=ProfileProductionStatus.UNSUPPORTED,
    evidence=PublisherAccessEvidence(
        display_name="MDPI",
        product_name="MDPI journals platform",
        official_references=(
            "https://www.mdpi.com/",
            "https://www.mdpi.com/about/openaccess",
            "https://www.mdpi.com/about/terms-and-conditions",
            "https://www.mdpi.com/robots.txt",
        ),
        access_terms_references=("https://www.mdpi.com/about/terms-and-conditions",),
        rate_limit_references=("https://www.mdpi.com/robots.txt",),
        verification_date=date(2026, 8, 15),
        evidence_revision="mdpi-public-route-unregistered-2026-08-15",
        notes_reference="docs/notes/providers/mdpi.md",
        fixture_reference="tests/fixtures/acquisition/profiles/mdpi.json",
    ),
)

NATURE_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="nature-portfolio",
    platform_key="nature",
    landing_origins=("https://www.nature.com",),
    asset_origins=("https://www.nature.com",),
    stable_locator_namespaces=(),
    provider_record_names=(),
    weak_doi_prefixes=("10.1038",),
    weak_publisher_names=("nature portfolio", "nature publishing group"),
    public_route_keys=(),
    api_route_keys=(),
    browser_route_key=None,
    browser_allowed_origins=(),
    browser_rate_limit_group=None,
    browser_session_key=None,
    browser_rule_id=None,
    browser_rule_revision=None,
    policy_evidence=PolicyEvidence.OFFICIAL,
    policy_revision="springer-nature-tdm-2026-08-15",
    production_status=ProfileProductionStatus.UNSUPPORTED,
    evidence=PublisherAccessEvidence(
        display_name="Nature Portfolio",
        product_name="Nature.com article platform",
        official_references=(
            "https://www.nature.com/",
            "https://www.nature.com/info/terms-and-conditions",
            "https://www.springernature.com/gp/researchers/text-and-data-mining",
        ),
        access_terms_references=("https://www.nature.com/info/terms-and-conditions",),
        rate_limit_references=(
            "https://www.springernature.com/gp/researchers/text-and-data-mining",
        ),
        verification_date=date(2026, 8, 15),
        evidence_revision="nature-browser-unsupported-2026-08-15",
        notes_reference="docs/notes/providers/springer-nature.md",
        fixture_reference="tests/fixtures/acquisition/profiles/nature-portfolio.json",
    ),
)

OXFORD_ACADEMIC_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="oxford-academic",
    platform_key="oxford-academic",
    landing_origins=("https://academic.oup.com",),
    asset_origins=("https://academic.oup.com",),
    stable_locator_namespaces=(),
    provider_record_names=(),
    weak_doi_prefixes=("10.1093",),
    weak_publisher_names=(
        "oxford academic",
        "oxford university press",
    ),
    public_route_keys=(),
    api_route_keys=(),
    browser_route_key=None,
    browser_allowed_origins=(),
    browser_rate_limit_group=None,
    browser_session_key=None,
    browser_rule_id=None,
    browser_rule_revision=None,
    policy_evidence=PolicyEvidence.OFFICIAL,
    policy_revision="oxford-academic-robots-2026-08-15",
    production_status=ProfileProductionStatus.UNSUPPORTED,
    evidence=PublisherAccessEvidence(
        display_name="Oxford Academic",
        product_name="Oxford Academic journals platform",
        official_references=(
            "https://academic.oup.com/",
            ("https://academic.oup.com/pages/open-research/text-and-data-mining"),
            "https://academic.oup.com/pages/standard-legal-terms-and-conditions",
            "https://academic.oup.com/pages/open-research/open-access",
            "https://academic.oup.com/robots.txt",
        ),
        access_terms_references=(
            "https://academic.oup.com/pages/standard-legal-terms-and-conditions",
            ("https://academic.oup.com/pages/open-research/text-and-data-mining"),
        ),
        rate_limit_references=("https://academic.oup.com/robots.txt",),
        verification_date=date(2026, 8, 15),
        evidence_revision="oxford-academic-automated-access-unsupported-2026-08-15",
        notes_reference="docs/notes/providers/oxford-academic.md",
        fixture_reference="tests/fixtures/acquisition/profiles/oxford-academic.json",
    ),
)

PNAS_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="pnas",
    platform_key="pnas",
    landing_origins=("https://www.pnas.org",),
    asset_origins=("https://www.pnas.org",),
    stable_locator_namespaces=(),
    provider_record_names=(),
    weak_doi_prefixes=("10.1073",),
    weak_publisher_names=(
        "pnas",
        "proceedings of the national academy of sciences",
    ),
    public_route_keys=(),
    api_route_keys=(),
    browser_route_key=None,
    browser_allowed_origins=(),
    browser_rate_limit_group=None,
    browser_session_key=None,
    browser_rule_id=None,
    browser_rule_revision=None,
    policy_evidence=PolicyEvidence.OFFICIAL,
    policy_revision="pnas-robots-2026-08-15",
    production_status=ProfileProductionStatus.UNSUPPORTED,
    evidence=PublisherAccessEvidence(
        display_name="PNAS",
        product_name="PNAS journals platform",
        official_references=(
            "https://www.pnas.org/",
            "https://www.pnas.org/about/terms-of-use",
            "https://www.pnas.org/about/open-access",
            "https://www.pnas.org/robots.txt",
        ),
        access_terms_references=("https://www.pnas.org/about/terms-of-use",),
        rate_limit_references=("https://www.pnas.org/robots.txt",),
        verification_date=date(2026, 8, 15),
        evidence_revision="pnas-automated-access-unsupported-2026-08-15",
        notes_reference="docs/notes/providers/pnas.md",
        fixture_reference="tests/fixtures/acquisition/profiles/pnas.json",
    ),
)

RSC_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="rsc-publishing",
    platform_key="rsc-publishing",
    landing_origins=("https://pubs.rsc.org",),
    asset_origins=("https://pubs.rsc.org",),
    stable_locator_namespaces=(),
    provider_record_names=(),
    weak_doi_prefixes=("10.1039",),
    weak_publisher_names=("royal society of chemistry", "rsc publishing"),
    public_route_keys=(),
    api_route_keys=(),
    browser_route_key=None,
    browser_allowed_origins=(),
    browser_rate_limit_group=None,
    browser_session_key=None,
    browser_rule_id=None,
    browser_rule_revision=None,
    policy_evidence=PolicyEvidence.OFFICIAL,
    policy_revision="rsc-machine-access-2026-08-15",
    production_status=ProfileProductionStatus.UNSUPPORTED,
    evidence=PublisherAccessEvidence(
        display_name="RSC Publishing",
        product_name="Royal Society of Chemistry publishing platform",
        official_references=(
            "https://pubs.rsc.org/",
            (
                "https://www.rsc.org/publishing/product-information/"
                "product-catalogue/text-and-data-mining"
            ),
            (
                "https://www.rsc.org/publishing/product-information/"
                "access-and-usage/terms-and-conditions"
            ),
        ),
        access_terms_references=(
            (
                "https://www.rsc.org/publishing/product-information/"
                "access-and-usage/terms-and-conditions"
            ),
        ),
        rate_limit_references=(
            (
                "https://www.rsc.org/publishing/product-information/"
                "product-catalogue/text-and-data-mining"
            ),
        ),
        verification_date=date(2026, 8, 15),
        evidence_revision="rsc-browser-unsupported-2026-08-15",
        notes_reference="docs/notes/providers/rsc.md",
        fixture_reference="tests/fixtures/acquisition/profiles/rsc-publishing.json",
    ),
)

PLOS_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="plos",
    platform_key="plos-journals",
    landing_origins=("https://journals.plos.org",),
    asset_origins=("https://journals.plos.org",),
    stable_locator_namespaces=(),
    provider_record_names=(),
    weak_doi_prefixes=("10.1371",),
    weak_publisher_names=(
        "plos",
        "public library of science",
    ),
    public_route_keys=(),
    api_route_keys=(),
    browser_route_key=None,
    browser_allowed_origins=(),
    browser_rate_limit_group=None,
    browser_session_key=None,
    browser_rule_id=None,
    browser_rule_revision=None,
    policy_evidence=PolicyEvidence.OFFICIAL,
    policy_revision="plos-journals-robots-2026-08-15",
    production_status=ProfileProductionStatus.UNSUPPORTED,
    evidence=PublisherAccessEvidence(
        display_name="PLOS",
        product_name="PLOS journals and public article access",
        official_references=(
            "https://plos.org/open-science/",
            "https://plos.org/terms-of-use/",
            "https://api.plos.org/",
            "https://api.plos.org/text-and-data-mining.html",
            "https://journals.plos.org/robots.txt",
        ),
        access_terms_references=("https://plos.org/terms-of-use/",),
        rate_limit_references=("https://journals.plos.org/robots.txt",),
        verification_date=date(2026, 8, 15),
        evidence_revision="plos-public-pdf-bulk-discouraged-2026-08-15",
        notes_reference="docs/notes/providers/plos.md",
        fixture_reference="tests/fixtures/acquisition/profiles/plos.json",
    ),
)

ROYAL_SOCIETY_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="royal-society-publishing",
    platform_key="royal-society-publishing",
    landing_origins=("https://royalsocietypublishing.org",),
    asset_origins=("https://royalsocietypublishing.org",),
    stable_locator_namespaces=(),
    provider_record_names=(),
    weak_doi_prefixes=("10.1098",),
    weak_publisher_names=(
        "royal society publishing",
        "the royal society journals",
    ),
    public_route_keys=(),
    api_route_keys=(),
    browser_route_key=None,
    browser_allowed_origins=(),
    browser_rate_limit_group=None,
    browser_session_key=None,
    browser_rule_id=None,
    browser_rule_revision=None,
    policy_evidence=PolicyEvidence.OFFICIAL,
    policy_revision="royal-society-public-policy-unreviewed-2026-08-15",
    production_status=ProfileProductionStatus.UNSUPPORTED,
    evidence=PublisherAccessEvidence(
        display_name="Royal Society Publishing",
        product_name="Royal Society Publishing journals platform",
        official_references=(
            "https://royalsocietypublishing.org/",
            "https://royalsocietypublishing.org/terms",
            "https://royalsociety.org/journals/open-access/",
            "https://royalsocietypublishing.org/robots.txt",
        ),
        access_terms_references=("https://royalsocietypublishing.org/terms",),
        rate_limit_references=("https://royalsocietypublishing.org/robots.txt",),
        verification_date=date(2026, 8, 15),
        evidence_revision="royal-society-automated-access-unsupported-2026-08-15",
        notes_reference="docs/notes/providers/royal-society-publishing.md",
        fixture_reference=("tests/fixtures/acquisition/profiles/royal-society-publishing.json"),
    ),
)

SCIENCE_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="science-aaas",
    platform_key="science-aaas",
    landing_origins=("https://www.science.org",),
    asset_origins=("https://www.science.org",),
    stable_locator_namespaces=(),
    provider_record_names=(),
    weak_doi_prefixes=("10.1126",),
    weak_publisher_names=(
        "aaas",
        "american association for the advancement of science",
        "science journals",
    ),
    public_route_keys=(),
    api_route_keys=(),
    browser_route_key=None,
    browser_allowed_origins=(),
    browser_rate_limit_group=None,
    browser_session_key=None,
    browser_rule_id=None,
    browser_rule_revision=None,
    policy_evidence=PolicyEvidence.OFFICIAL,
    policy_revision="science-aaas-robots-2026-08-15",
    production_status=ProfileProductionStatus.UNSUPPORTED,
    evidence=PublisherAccessEvidence(
        display_name="Science / AAAS",
        product_name="Science journals platform",
        official_references=(
            "https://www.science.org/",
            "https://www.aaas.org/terms",
            "https://www.science.org/content/page/terms-use",
            "https://www.science.org/content/page/open-access-aaas",
            "https://www.science.org/robots.txt",
        ),
        access_terms_references=(
            "https://www.aaas.org/terms",
            "https://www.science.org/content/page/terms-use",
        ),
        rate_limit_references=("https://www.science.org/robots.txt",),
        verification_date=date(2026, 8, 15),
        evidence_revision="science-aaas-automated-access-unsupported-2026-08-15",
        notes_reference="docs/notes/providers/science-aaas.md",
        fixture_reference="tests/fixtures/acquisition/profiles/science-aaas.json",
    ),
)

SPRINGERLINK_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="springerlink",
    platform_key="springerlink",
    landing_origins=("https://link.springer.com",),
    asset_origins=(
        "https://link.springer.com",
        "https://static-content.springer.com",
    ),
    stable_locator_namespaces=("doi",),
    provider_record_names=(),
    weak_doi_prefixes=("10.1007",),
    weak_publisher_names=("springer", "springerlink"),
    public_route_keys=(),
    api_route_keys=(),
    browser_route_key="browser:springerlink",
    browser_allowed_origins=(
        "https://link.springer.com",
        "https://static-content.springer.com",
        "https://idp.springer.com",
        "https://wayf.springernature.com",
    ),
    browser_rate_limit_group="springerlink",
    browser_session_key="springerlink",
    browser_rule_id="springerlink-pdf",
    browser_rule_revision=4,
    policy_evidence=PolicyEvidence.OFFICIAL,
    policy_revision="springerlink-browser-tdm-v1",
    production_status=ProfileProductionStatus.PRODUCTION_READY,
    evidence=PublisherAccessEvidence(
        display_name="Springer Nature Link",
        product_name="Springer Nature Link article platform",
        official_references=(
            "https://link.springer.com/",
            "https://link.springer.com/termsandconditions",
            "https://www.springernature.com/gp/researchers/text-and-data-mining",
        ),
        access_terms_references=("https://link.springer.com/termsandconditions",),
        rate_limit_references=(
            "https://www.springernature.com/gp/researchers/text-and-data-mining",
        ),
        verification_date=date(2026, 8, 18),
        evidence_revision="springerlink-browser-pdf-v4-2026-08-18",
        notes_reference="docs/notes/providers/springer-nature.md",
        fixture_reference="tests/fixtures/acquisition/profiles/springerlink.json",
    ),
    browser_policy=BrowserGroupPolicy(
        rate_limit_group="springerlink",
        policy_revision="springerlink-browser-tdm-v1",
        minimum_start_interval=10.0,
        rate_limit_cooldown=300.0,
        runtime_failure_threshold=2,
        cooldown_after_completion=0.0,
        failure_cooldown=60.0,
    ),
)

WILEY_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="wiley-online-library",
    platform_key="wiley-online-library",
    landing_origins=("https://onlinelibrary.wiley.com",),
    asset_origins=(
        "https://onlinelibrary.wiley.com",
        "https://alm.wiley.com",
    ),
    stable_locator_namespaces=(),
    provider_record_names=("wiley",),
    weak_doi_prefixes=("10.1002",),
    weak_publisher_names=("wiley",),
    public_route_keys=(),
    api_route_keys=("api:wiley-tdm-v1",),
    browser_route_key=None,
    browser_allowed_origins=(),
    browser_rate_limit_group=None,
    browser_session_key=None,
    browser_rule_id=None,
    browser_rule_revision=None,
    policy_evidence=PolicyEvidence.OFFICIAL,
    policy_revision="wiley-tdm-v1-client-1.2.0-2026-08-13",
    production_status=ProfileProductionStatus.PRODUCTION_READY,
    evidence=PublisherAccessEvidence(
        display_name="Wiley Online Library",
        product_name="Wiley Online Library TDM API v1",
        official_references=(
            "https://onlinelibrary.wiley.com/library-info/resources/text-and-datamining",
            "https://github.com/WileyLabs/tdm-client",
            "https://static.wiley.com/tdm/",
        ),
        access_terms_references=(
            "https://onlinelibrary.wiley.com/library-info/resources/text-and-datamining",
        ),
        rate_limit_references=("https://github.com/WileyLabs/tdm-client",),
        verification_date=date(2026, 8, 15),
        evidence_revision="wiley-tdm-v1-client-1.2.0-2026-08-15",
        notes_reference="docs/notes/providers/wiley.md",
        fixture_reference="tests/fixtures/acquisition/profiles/wiley-online-library.json",
    ),
)

WORLD_SCIENTIFIC_ACCESS_PROFILE: Final[PublisherAccessProfile] = PublisherAccessProfile(
    access_key="world-scientific",
    platform_key="world-scientific",
    landing_origins=("https://www.worldscientific.com",),
    asset_origins=("https://www.worldscientific.com",),
    stable_locator_namespaces=(),
    provider_record_names=(),
    weak_doi_prefixes=("10.1142",),
    weak_publisher_names=("world scientific",),
    public_route_keys=(),
    api_route_keys=(),
    browser_route_key=None,
    browser_allowed_origins=(),
    browser_rate_limit_group=None,
    browser_session_key=None,
    browser_rule_id=None,
    browser_rule_revision=None,
    policy_evidence=PolicyEvidence.OFFICIAL,
    policy_revision="world-scientific-robots-2026-08-15",
    production_status=ProfileProductionStatus.UNSUPPORTED,
    evidence=PublisherAccessEvidence(
        display_name="World Scientific",
        product_name="World Scientific journals platform",
        official_references=(
            "https://www.worldscientific.com/",
            "https://www.worldscientific.com/page/terms-and-conditions",
            "https://www.worldscientific.com/robots.txt",
        ),
        access_terms_references=("https://www.worldscientific.com/page/terms-and-conditions",),
        rate_limit_references=("https://www.worldscientific.com/robots.txt",),
        verification_date=date(2026, 8, 15),
        evidence_revision="world-scientific-automated-access-unsupported-2026-08-15",
        notes_reference="docs/notes/providers/world-scientific.md",
        fixture_reference="tests/fixtures/acquisition/profiles/world-scientific.json",
    ),
)

PUBLISHER_ACCESS_VERIFICATION_MATRIX: Final[PublisherAccessVerificationMatrix] = (
    PublisherAccessVerificationMatrix(
        profiles=PublisherAccessProfileCatalog(
            (
                ACM_ACCESS_PROFILE,
                ACS_ACCESS_PROFILE,
                AIP_ACCESS_PROFILE,
                AMERICAN_MATHEMATICAL_SOCIETY_ACCESS_PROFILE,
                ANNUAL_REVIEWS_ACCESS_PROFILE,
                APS_ACCESS_PROFILE,
                COPERNICUS_ACCESS_PROFILE,
                CORE_ACCESS_PROFILE,
                ELSEVIER_ACCESS_PROFILE,
                FRONTIERS_ACCESS_PROFILE,
                IEEE_ACCESS_PROFILE,
                IOP_ACCESS_PROFILE,
                MDPI_ACCESS_PROFILE,
                NATURE_ACCESS_PROFILE,
                OXFORD_ACADEMIC_ACCESS_PROFILE,
                PNAS_ACCESS_PROFILE,
                PLOS_ACCESS_PROFILE,
                ROYAL_SOCIETY_ACCESS_PROFILE,
                RSC_ACCESS_PROFILE,
                SCIENCE_ACCESS_PROFILE,
                SPRINGERLINK_ACCESS_PROFILE,
                WILEY_ACCESS_PROFILE,
                WORLD_SCIENTIFIC_ACCESS_PROFILE,
            )
        ),
        browser_rules=PRODUCTION_BROWSER_RULE_CATALOG,
    )
)
PRODUCTION_PUBLISHER_ACCESS_PROFILE_CATALOG: Final[PublisherAccessProfileCatalog] = (
    PUBLISHER_ACCESS_VERIFICATION_MATRIX.production_profiles
)


__all__ = (
    "ACM_ACCESS_PROFILE",
    "ACS_ACCESS_PROFILE",
    "AIP_ACCESS_PROFILE",
    "AMERICAN_MATHEMATICAL_SOCIETY_ACCESS_PROFILE",
    "ANNUAL_REVIEWS_ACCESS_PROFILE",
    "APS_ACCESS_PROFILE",
    "COPERNICUS_ACCESS_PROFILE",
    "CORE_ACCESS_PROFILE",
    "ELSEVIER_ACCESS_PROFILE",
    "FRONTIERS_ACCESS_PROFILE",
    "IEEE_ACCESS_PROFILE",
    "IOP_ACCESS_PROFILE",
    "MDPI_ACCESS_PROFILE",
    "NATURE_ACCESS_PROFILE",
    "OXFORD_ACADEMIC_ACCESS_PROFILE",
    "PNAS_ACCESS_PROFILE",
    "PLOS_ACCESS_PROFILE",
    "PUBLISHER_ACCESS_VERIFICATION_MATRIX",
    "PRODUCTION_PUBLISHER_ACCESS_PROFILE_CATALOG",
    "RSC_ACCESS_PROFILE",
    "ROYAL_SOCIETY_ACCESS_PROFILE",
    "SCIENCE_ACCESS_PROFILE",
    "SPRINGERLINK_ACCESS_PROFILE",
    "WILEY_ACCESS_PROFILE",
    "WORLD_SCIENTIFIC_ACCESS_PROFILE",
)
